### ISSUE TITLE
Error during launcher installation

### ISSUE THREAD

**Issue by lutzgooren** [moraroy/NonSteamLaunchersDecky#8] opened 2024-05-17 07:26 UTC
Installation through decky plugin fails for me - Desktop install works fine.
Throws error "Cannot read properties of null (reading 'autoscan')"

Steam Deck is currently running on the 3.6.3 preview with decky loader 2.12.0-pre1
Plugin logs: 
[2024-05-17 09.04.38.log](https://github.com/moraroy/NonSteamLaunchersDecky/files/15345205/2024-05-17.09.04.38.log)

**Comment by moraroy** [comment] 2024-05-18 20:53
@sysmoon14

**Comment by Z-ANESaber** [comment] 2024-06-18 13:49
I had the same issue. Fixed it by switching to the Deck's stable channel

**Comment by moraroy** [comment] 2024-07-05 01:15
@Z-ANESaber @lutzgooren was this still an issue for you guys in the latest version?

**Comment by Z-ANESaber** [comment] 2024-07-05 15:29
I have done some extensive testing with the latest version now and even though I didn't get the error anymore it still would not finish installing and it just stays stuck in the installing window. 

Interestingly while that install window is looping you can still interact with the operating system in the background.

Tried it in the Steam Deck Preview and Beta channel. 
The 3 launchers I always install are Ubisoft Connect, EA App and RockstarGames Launcher.

**So I tried:**
- Installing every launcher one at a time
- Installing everything at once with the same app id
- Installing everything at once with separate app ids checked
- All of the above on different wifis, ethernet, dns, vpns and so on

And all of that on the Preview, Beta and Stable channel and only the Stable channel worked.
What did seem to work however was switching to the stable channel, installing the launchers you need and then switching back to preview or beta channel.

### Versions
- Decky v3.0.0 pre3
- NonSteamLaunchers 1.0.0-1aded71
- Steam Deck Stable, Beta and Preview channel versions from 05/07/2024

**Comment by moraroy** [comment] 2024-07-06 00:05
@Z-ANESaber interestingly, admittedly i never go on the beta or preview versions of steamos, i stick to stable mostly. the next time i wipe my deck for testing ill test NSL on these channels and see why they arent installing, thank you for testing this!

**Comment by moraroy** [comment] 2024-07-06 06:00
@Z-ANESaber if you go in desktop mode, and in your Downloads folder, you can probably see what's going on in the NSL log. It may give an error why things aren't installing in anything but stable

**Comment by Z-ANESaber** [comment] 2024-07-06 11:33
I did try that now but there are no logs being created because nothing actually crashes or finishes and just stays stuck forever so I sadly couldn't take a look at that.

**Comment by moraroy** [comment] 2024-07-06 11:45
@Z-ANESaber oh OK that's kind of good news in a way, it means that the script is even being run. So the issue, sounds like it's plugin related. There is another log you can check, the actual plugin log, this is located i think home/deck/homebrew/plugins/logs? I think around there it would have NonSteamLaunchers as a folder

**Comment by Z-ANESaber** [comment] 2024-07-06 12:05
I tested that now. The path was slightly different but i could still find it. There were multiple logs in there but they were almost all identical with only two variations which I added below. I hope those help.

[2024-07-06 13.23.38.log](https://github.com/user-attachments/files/16115940/2024-07-06.13.23.38.log)
[2024-07-05 16.29.46.log](https://github.com/user-attachments/files/16115941/2024-07-05.16.29.46.log)

**Comment by moraroy** [comment] 2024-07-06 12:11
@Z-ANESaber I don't see any errors in the second.log, but the first one I see the problem. Lol it's that same dumb module error that was recently fixed in the desktop version, same reason too, and makes sense why it only works in stable. For some reason, in preview and beta, that module has been removed on those channels but in stable it is there. I'll do my best to add that module in and that should fix those errors for those branches. Here is a link to the fix for the desktop version, if you wanted more info https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/issues/296#issuecomment-2119206614

**Comment by Z-ANESaber** [comment] 2024-07-06 15:27
I see, that's good to hear. Once an update comes out I'll be sure to test it out on both channels

**Comment by moraroy** [comment] 2024-07-07 00:55
@Z-ANESaber hey bro just added the fix in https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/527 not sure when it will go live but keep an eye on the testing store for the update!

**Comment by Z-ANESaber** [comment] 2024-07-31 15:05
Ok so the update was applied now and I noticed that while it did fix the downloading freeze issue, the shortcuts never appeared and the the installation was so unbelievably fast that I doubt anything even installed.
**I have only tested this in the beta and preview channels.**

Additionally after updating to the new version my previously installed games from my previously installed launchers did appear now so the AutoGameScanner did not seem to work previously on beta and preview. But every game shortcut appeared twice and Ubisoft Connect in particular was always reappearing even after uninstalling so I had to start fresh. This only happened one time however so it should not be a big deal.

I have attached two log files, one is after starting fresh and the other was before and while I also had the weird shortcut duplication.
Hope this helps!

[2024-07-31 13.38.21.log](https://github.com/user-attachments/files/16443725/2024-07-31.13.38.21.log)
[2024-07-31 13.34.48.log](https://github.com/user-attachments/files/16443726/2024-07-31.13.34.48.log)

**Comment by moraroy** [comment] 2024-07-31 21:49
@Z-ANESaber ok thank you yes that's helpful, I think the duplication doesn't happen if you delete your old shortcuts, for some reason when auto scan is on it sometimes does that I need to figure out why haha

**Comment by Z-ANESaber** [comment] 2024-08-03 18:00
Yeah the duplication was not an issue anymore on those last two versions that came out the last few days.

I actually tested the last two versions of the plugin and I made logs for each. The previous version (1.0.0-2ae00ce) had the issue that installing takes pretty long to the point where I thought it was stuck again but it did work after waiting.

The latest version works flawless on preview channel. Only the auto scanner seems to add the shortcuts for games a little late. In my case I installed one game from EA, the shortcut didn't appear and after I installed a second game from EA then both appeared. And the installation of launchers takes longer than usual so maybe, if possible, adding a progress bar would help to prevent people from thinking it is stuck.

I added logs for both the previous version (1.0.0-2ae00ce) and the latest (1.0.0-5fc13b6)

[LATEST 2024-08-03 13.23.50.log](https://github.com/user-attachments/files/16482392/LATEST.2024-08-03.13.23.50.log)
[LATEST 2024-08-03 13.24.00.log](https://github.com/user-attachments/files/16482394/LATEST.2024-08-03.13.24.00.log)
[LATEST NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16482395/LATEST.NonSteamLaunchers-install.log)

[PREVIOUS 2024-08-02 21.51.00.log](https://github.com/user-attachments/files/16482396/PREVIOUS.2024-08-02.21.51.00.log)
[PREVIOUS 2024-08-02 21.56.54.log](https://github.com/user-attachments/files/16482397/PREVIOUS.2024-08-02.21.56.54.log)
[PREVIOUS NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16482398/PREVIOUS.NonSteamLaunchers-install.log)

**Comment by moraroy** [comment] 2024-08-04 01:20
@Z-ANESaber that sounds like a good idea, tha k you for taking the time to provide logs it's very helpful. As of right now the current and latest version should work on stable and preview it seems. I'm having some trouble with GOG on beta though still trying to figure out why the x server is failing.

**Comment by Z-ANESaber** [comment] 2024-08-04 12:33
I can confirm that.
I have just tried it on beta too and it was loading forever.

**Comment by moraroy** [comment] 2024-08-04 12:38
@Z-ANESaber I pushed a fix already https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/527

**Comment by Z-ANESaber** [comment] 2024-08-04 16:03
I see. Well then it seems to be good. I don't have a GOG account to test it with games though so that's all I can say.

**Comment by moraroy** [comment] 2024-08-04 23:51
@Z-ANESaber once gog is working, I'm going to attempt to implement your idea as well as add a cool down system on the scanner between the manual and auto toggle, I'm also going to add some very helpful UI changes that hopefully will help.

**Comment by moraroy** [comment] 2024-08-05 22:54
@Z-ANESaber I belive the fixes are in! Let me know

**Comment by Z-ANESaber** [comment] 2024-08-06 13:21
I can confirm GOG is installing perfectly fine now. As for speed nothing has changed (not sure if something is supposed to be different on that yet but still thought I'd mention).
I went ahead and timed it with a stopwatch now for future reference on speed improvements. 
The time it took me to install GOG on Wifi was 1 minute 15 seconds.

But since everything installs now the issue should be solved.

**Comment by moraroy** [comment] 2024-08-07 06:38
@Z-ANESaber the time it takes could be a lot of reasons, wifi speed etc, but it sounds like maybe the installation process is timing out all the way for some reason, the installation log will be in your downloads folder when you install gog, it will tell you how long it takes

**Comment by moraroy** [comment] 2024-08-11 04:56
im going to close this as this has been fixed for the main reasons on stable, beta and pre

**Closed by moraroy** 2024-08-11 04:56 UTC
