### ISSUE TITLE
EA App Install never finishes on beta/pre

### ISSUE THREAD

**Issue by felipecrs** [moraroy/NonSteamLaunchersDecky#16] opened 2024-08-17 03:05 UTC
I just installed the Decky Plugin now, Steam OS Beta 3.5.10, and no matter what I try to add, launcher, web shortcuts, it just keeps spinning but nothing happens.

There is no cancel button, so I have to force restart my Steam Deck to get out of it.

Note that I'm a new user. Did I do something wrong?

**Comment by moraroy** [comment] 2024-08-17 03:14
@felipecrs no you did nothing wrong, make sure you have chrome installed and the latest proton GE and then try again. I re-imaged my deck when the plugin came out and was able to do eveything on the first try. Try restarting the deck and let me know if that works. I fear there may be an issue with the websocket coding in the plugin that seems to be failing as the modal isnt closing. Not sure what the cause is yet.

**Comment by felipecrs** [comment] 2024-08-17 03:16
Oh, ok. Let me try.

PS: I have no Chrome installed, neither Proton GE. Will install.

**Comment by moraroy** [comment] 2024-08-17 03:22
@felipecrs the plugin attempts to do this for you, but its very possible i missed something for the beta branch, sorry about that

**Comment by felipecrs** [comment] 2024-08-17 03:29
Don't worry!

Ok, it works now. I installed both Chrome from Discover and latest Proton GE from ProtonUp Qt.

In fact, I found in my downloads folder some files related to Proton GE, so it looks like it was indeed attempted to install.

Also, I found the .log there. I saw the flatpak command to install Chrome, it reaches 100%, but then no more logs.

Interesting. Not sure what went wrong, but it's working now.

If you want I can try uninstalling stuff to try to reproduce it, but otherwise, an option to cancel the operation would be nice at least.

Also, perhaps some indicator that it's trying to install Chrome or either Proton GE (because if I knew it, I could have attempted to install them myself and then issue would be gone)

Nevertheless thank you very much for the kindness and the prompt help!

**Comment by moraroy** [comment] 2024-08-17 03:34
@felipecrs could you upload the log here? That would help alot for me! A good plugin that works well with NonsteamLaunchers is Wine Cellar. That way you dont have to use ProtonUpQt nor leave game mode! Whenever i get a chance to update im going to be putting ina real time log as it installs so no worries there. That way people can see whats going on

**Comment by felipecrs** [comment] 2024-08-17 03:43
I can actually reproduce the issue when trying to install EA App (when I said it was working now, was to add Netflix only - which for sure should be related to installing Chrome flatpak).

Let me let it spin for some time to make sure I am not cancelling something that's working.

Any ideas how long normally installing EA App should take on this screen?

![20240817_004310.jpg](https://github.com/user-attachments/assets/d01056bb-e21e-46db-9444-14a24812fcbb)

Less than 5 minutes for example?

**Comment by moraroy** [comment] 2024-08-17 03:46
@felipecrs dang no launcher should take more than 5 minutes on a stable internet. Maybe the new beta branch update blocked something not sure... im going to go back on the beta bracnh myself and test

**Comment by moraroy** [comment] 2024-08-17 03:48
@felipecrs could you upload the log first i might have to see whats wrong there first

**Comment by felipecrs** [comment] 2024-08-17 04:01
For sure! Hold on

**Comment by felipecrs** [comment] 2024-08-17 04:03
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16643299/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment] 2024-08-17 04:22
@felipecrs youre using the main store decky plugin right, not the one in the testing store?

**Comment by felipecrs** [comment] 2024-08-17 04:25
Hm... I forgot to mention I'm using Decky pre-release.

However, I didn't even know there was two different stores for Decky.

I installed Decky, booted into Gaming Mode, opened it, opened the store icon and installed NonSteamLaunchers.

I guess I'm using the main store.

**Comment by moraroy** [comment] 2024-08-17 04:28
Gotcha, so pre-release decky, main store NSL. Ok thank you that helps. I see the problem. Not sure how to fix yet, this is a beta branch issue of steamos i believe

**Comment by moraroy** [comment] 2024-08-17 04:28
Gotcha, so pre-release decky, main store NSL. Ok thank you that helps. I see the problem. Not sure how to fix yet, this is a beta branch issue of steamos i believe

**Comment by moraroy** [comment] 2024-08-17 05:00
@felipecrs is it just the ea app? Or are you able to install other things?

**Comment by remilopes** [comment] 2024-08-17 05:13
I only tried like 4, ea was the only one with issues. Everything on stable on my end.

**Comment by moraroy** [comment] 2024-08-17 05:19
@remilopes thats good news. I know what the problem is and ill try to push an update soon thank you.

**Comment by SerhiyZSP** [comment] 2024-08-18 02:52
Hi. I have same issue with EA App (Decky pre-release, main store). Other several launchers installed without problems. Thank you for the fix in advance.

**Comment by moraroy** [comment] 2024-08-24 07:09
@felipecrs @SerhiyZSP try the testing store version 1.0.1 let me know how it goes

**Comment by SerhiyZSP** [comment] 2024-08-25 09:37
Hello.I installed update and tryed to install EA app. I reseived message that app installed and in liberary I can see Repeir 
EA app. But this app not starting.
![20240825112525_1](https://github.com/user-attachments/assets/f92efc41-a02d-48e9-b387-95a5c8ed2b06)
![20240825112535_1](https://github.com/user-attachments/assets/ddd7fa49-b4c3-4e97-afd6-7b11ca5d3f9f)

**Comment by moraroy** [comment] 2024-08-25 09:46
@remilopes restart your deck and then try to run it?

**Comment by SerhiyZSP** [comment] 2024-08-25 11:30
Yes, after restart it start working and EA app appeared in library. Thanks.

**Comment by remilopes** [comment] 2024-08-25 11:39
Hello again, The EA App installed without issues but the shortcut was added 4 times.
Launched and connected without any issue, installed a random game successfully but shortcut was added twice.
Installed a second random game which again launched successfully but shortcut was added twice as well.

**Comment by moraroy** [comment] 2024-08-25 11:41
@remilopes yeah ill be fixing that soon, just delete the shortcuts and then they dont come back, i put new info inside the new shortcuts, so it looks like its duplicating the shortcuts, if that makes sense haha

**Comment by remilopes** [comment] 2024-08-25 12:17
Yeah it's such an insignificant problem compared to what it was... Thank you for your work !

**Comment by moraroy** [comment] 2024-09-06 06:37
@felipecrs @remilopes @SerhiyZSP the current version in the testing store seems like a good candidate, let me know what you guys think

**Comment by felipecrs** [comment] 2024-09-06 14:18
@moraroy I only tested it today, and EA App installed just fine. Thanks a lot!

One small issue is that the EA App window is too big when opened in gaming mode. It doesn't allow me to press the OK button for the 2-factor authentication.

There's no way to scroll, either by touchscreen or mouse scroll. Weird. Haven't you guys faced the same?

![20240906_111100](https://github.com/user-attachments/assets/757b232e-27e2-4b55-bf4e-1fb7dd6d2526)

**Comment by felipecrs** [comment] 2024-09-06 14:18
@moraroy but go ahead and release it, it definitely fixed this issue. Feel free to close this ticket even.

**Comment by moraroy** [comment] 2024-09-06 19:52
@felipecrs yes, you wiped everything. It's as if you pressed Start Fresh

**Closed** 2024-09-06 19:53 UTC
Labels: bug
